//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatteryMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charging.
        /// </summary>
        public static string ChargeStatusCharging {
            get {
                return ResourceManager.GetString("ChargeStatusCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to critical.
        /// </summary>
        public static string ChargeStatusCritical {
            get {
                return ResourceManager.GetString("ChargeStatusCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high.
        /// </summary>
        public static string ChargeStatusHigh {
            get {
                return ResourceManager.GetString("ChargeStatusHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low.
        /// </summary>
        public static string ChargeStatusLow {
            get {
                return ResourceManager.GetString("ChargeStatusLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no system battery.
        /// </summary>
        public static string ChargeStatusNoSystemBattery {
            get {
                return ResourceManager.GetString("ChargeStatusNoSystemBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string ChargeStatusOk {
            get {
                return ResourceManager.GetString("ChargeStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string ChargeStatusUnknown {
            get {
                return ResourceManager.GetString("ChargeStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium Ion.
        /// </summary>
        public static string ChemistryLiIo {
            get {
                return ResourceManager.GetString("ChemistryLiIo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium Polymer.
        /// </summary>
        public static string ChemistryLiPo {
            get {
                return ResourceManager.GetString("ChemistryLiPo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickel Cadmium.
        /// </summary>
        public static string ChemistryNiCd {
            get {
                return ResourceManager.GetString("ChemistryNiCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickel Metal Hydride.
        /// </summary>
        public static string ChemistryNiMH {
            get {
                return ResourceManager.GetString("ChemistryNiMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickel Zinc.
        /// </summary>
        public static string ChemistryNiZn {
            get {
                return ResourceManager.GetString("ChemistryNiZn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Acid.
        /// </summary>
        public static string ChemistryPbAc {
            get {
                return ResourceManager.GetString("ChemistryPbAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechargeable Alkaline-Manganese.
        /// </summary>
        public static string ChemistryRAM {
            get {
                return ResourceManager.GetString("ChemistryRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m-d-yyyy.
        /// </summary>
        public static string FormatDate {
            get {
                return ResourceManager.GetString("FormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        public static string HeaderBattery {
            get {
                return ResourceManager.GetString("HeaderBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string HeaderSystem {
            get {
                return ResourceManager.GetString("HeaderSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Health.
        /// </summary>
        public static string LabelBatteryHealth {
            get {
                return ResourceManager.GetString("LabelBatteryHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Name.
        /// </summary>
        public static string LabelBatteryName {
            get {
                return ResourceManager.GetString("LabelBatteryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string LabelCapacity {
            get {
                return ResourceManager.GetString("LabelCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge State.
        /// </summary>
        public static string LabelChargeState {
            get {
                return ResourceManager.GetString("LabelChargeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemistry.
        /// </summary>
        public static string LabelChemistry {
            get {
                return ResourceManager.GetString("LabelChemistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Bias.
        /// </summary>
        public static string LabelCriticalBias {
            get {
                return ResourceManager.GetString("LabelCriticalBias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Capacity.
        /// </summary>
        public static string LabelCurrentCapacity {
            get {
                return ResourceManager.GetString("LabelCurrentCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Count.
        /// </summary>
        public static string LabelCycleCount {
            get {
                return ResourceManager.GetString("LabelCycleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Capacity Limit 1.
        /// </summary>
        public static string LabelDefaultAlert1 {
            get {
                return ResourceManager.GetString("LabelDefaultAlert1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Capacity Limit 2.
        /// </summary>
        public static string LabelDefaultAlert2 {
            get {
                return ResourceManager.GetString("LabelDefaultAlert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed Capacity.
        /// </summary>
        public static string LabelDesignCapacity {
            get {
                return ResourceManager.GetString("LabelDesignCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Charge Capacity.
        /// </summary>
        public static string LabelFullChargedCapacity {
            get {
                return ResourceManager.GetString("LabelFullChargedCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture Date.
        /// </summary>
        public static string LabelManufactureDate {
            get {
                return ResourceManager.GetString("LabelManufactureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string LabelManufacturer {
            get {
                return ResourceManager.GetString("LabelManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Line Status.
        /// </summary>
        public static string LabelPowerLineStatus {
            get {
                return ResourceManager.GetString("LabelPowerLineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power State.
        /// </summary>
        public static string LabelPowerState {
            get {
                return ResourceManager.GetString("LabelPowerState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge/Discharge Rate.
        /// </summary>
        public static string LabelRate {
            get {
                return ResourceManager.GetString("LabelRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaing time.
        /// </summary>
        public static string LabelRemainingTime {
            get {
                return ResourceManager.GetString("LabelRemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string LabelTemperature {
            get {
                return ResourceManager.GetString("LabelTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        public static string LabelVoltage {
            get {
                return ResourceManager.GetString("LabelVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offline.
        /// </summary>
        public static string PowerLineStateOffline {
            get {
                return ResourceManager.GetString("PowerLineStateOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online.
        /// </summary>
        public static string PowerLineStateOnline {
            get {
                return ResourceManager.GetString("PowerLineStateOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charging.
        /// </summary>
        public static string PowerStateCharging {
            get {
                return ResourceManager.GetString("PowerStateCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to critical.
        /// </summary>
        public static string PowerStateCritical {
            get {
                return ResourceManager.GetString("PowerStateCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discharging.
        /// </summary>
        public static string PowerStateDischarging {
            get {
                return ResourceManager.GetString("PowerStateDischarging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugged in.
        /// </summary>
        public static string PowerStatePluggedIn {
            get {
                return ResourceManager.GetString("PowerStatePluggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Monitor.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
